name: build
on:
  push:

jobs:
  build-client:
    runs-on: serv-runner-set
    steps:
      - run: sudo apt update && sudo apt install -yyqq curl clang libssl-dev pkg-config
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --bin=serv-client
  build-server:
    runs-on: serv-runner-set
    steps:
      - run: sudo apt update && sudo apt install -yyqq curl clang libssl-dev pkg-config
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --bin=serv-server
